services:
  postgres:
    container_name: postgres-sql-fssch
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: flight_school_schedule
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-fs
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-fssch
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-fs:
    driver: bridge

volumes:
  postgres:
    driver: local
